# Generated by Django 3.2.15 on 2022-09-29 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0003_auto_20220929_1507'),
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='msg',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_lists',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='medium.favoritelist'),
            preserve_default=False,
        ),
    ]
