# Generated by Django 3.2.15 on 2022-10-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0002_customuser_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorites',
        ),
    ]
