POST http://127.0.0.1:8000/auth/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin00",
    "password": "Aze1232000+"
}
### Verifying Email -> Done
POST http://127.0.0.1:8000/auth/registration/verify-email/ HTTP/1.1
Content-Type: application/json

{
    "key": "MTc:1od7Wo:E78STMTiC5TB9UVHj6L0FaUb6E9rqePHaMmXqs_tXiY"
}
### Change Password -> Done
GET http://127.0.0.1:8000/api/article/7/card-title55/ HTTP/1.1
Content-Type: application/json
Authorization: Token 50c3bcb766ce3734be5258b69ff7706245e07375
