# Generated by Django 3.2.15 on 2022-10-01 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0002_alter_favoritelist_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='articles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medium.article'),
        ),
    ]
