# Generated by Django 3.2.15 on 2022-10-01 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userAccount', '0003_remove_customuser_favorites'),
        ('medium', '0003_alter_favoritelist_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FavoriteList',
        ),
    ]
